### ISSUE TITLE
Exception thrown while writing using stocator.

### ISSUE THREAD

**Issue by ScrapCodes** [CODAIT/stocator#209]
On executing the following command with the latest version of stocator(9c1c6932018e96725ed833d93647095261ed894e) and Spark (master version) running with --master local[60],

```scala
spark.range(0,1000000, 1, 100000).selectExpr("id", "id < 100 as p").write.partitionBy("p").mode("Overwrite").save("cos://<path_hidden>")
```

After completing a X number of tasks, following error pops up. It seems to be from stocator. X varies from 400 to 3500.

```
Caused by: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
  at java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1835)
  at java.util.HashMap$TreeNode.putTreeVal(HashMap.java:2014)
  at java.util.HashMap.putVal(HashMap.java:638)
  at java.util.HashMap.put(HashMap.java:612)
  at com.ibm.stocator.fs.cos.COSAPIClient.getFileStatusKeyBased(COSAPIClient.java:597)
  at com.ibm.stocator.fs.cos.COSAPIClient.getFileStatus(COSAPIClient.java:516)
  at com.ibm.stocator.fs.ObjectStoreFileSystem.getFileStatus(ObjectStoreFileSystem.java:515)
  at org.apache.spark.sql.execution.datasources.BasicWriteTaskStatsTracker.getFileSize(BasicWriteStatsTracker.scala:68)
  at org.apache.spark.sql.execution.datasources.BasicWriteTaskStatsTracker.$anonfun$statCurrentFile$1(BasicWriteStatsTracker.scala:94)
  at org.apache.spark.sql.execution.datasources.BasicWriteTaskStatsTracker.$anonfun$statCurrentFile$1$adapted(BasicWriteStatsTracker.scala:93)
  at scala.Option.foreach(Option.scala:274)
```

**Comment by gilv** [comment]
@ScrapCodes thanks for reporting this. Checking what is wrong.

**Comment by gilv** [comment]
@ScrapCodes I wonder why exception comes out of Java itself.
Caused by: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode

what is JDK version being used?

**Comment by ScrapCodes** [comment]
After reducing the thread count from 60 to 16, the problem is so far not observed (45k tasks completed and still ticking).
JDK version: javac 1.8.0_212
on centos 7.

**Comment by gilv** [comment]
@ScrapCodes interesting..will try to reproduce this issue. thanks

**Comment by michaelaltar** [comment]
Same problem reproduced. 
Submit pull request https://github.com/CODAIT/stocator/pull/212
