### ISSUE TITLE
Error when querying for data using stocator.

### ISSUE THREAD

**Issue by bharath0208** [CODAIT/stocator#218]
Hi Team,

I am trying to query data in IBM COS by using a SQL engine tool and it fails. It works fine when I use s3a file system way of creating tables and querying the data. I implemented stocator to get the multi-cos support but I see that the query fails. It works fine if i am bringing it down to 110GB. Also if I double the number of resources than the one i was using for s3a it seems to be working fine. Kindly advice.

DataType: Parquet
Dataset Size:140 GB

**Error**

Query 20190909_203915_00057_c8rpc failed: Error reading from cos://bucketName.instanceName/lineitem/20190729_173848_00087_ic489_646a5f6a-00cd-48f6-8991-2a3dfa4c3427 at position 1831791759
io.prestosql.spi.PrestoException: Error reading from cos://bucketName.instanceName/lineitem/20190729_173848_00087_ic489_646a5f6a-00cd-48f6-8991-2a3dfa4c3427 at position 1831791759
	at io.prestosql.plugin.hive.parquet.HdfsParquetDataSource.readInternal(HdfsParquetDataSource.java:111)
	at io.prestosql.plugin.hive.parquet.HdfsParquetDataSource.readFully(HdfsParquetDataSource.java:94)
	at io.prestosql.plugin.hive.parquet.HdfsParquetDataSource.readFully(HdfsParquetDataSource.java:85)
	at io.prestosql.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:219)
	at io.prestosql.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:284)
	at io.prestosql.parquet.reader.ParquetReader.readBlock(ParquetReader.java:267)
	at io.prestosql.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:241)
	at io.prestosql.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:219)
	at io.prestosql.spi.block.LazyBlock.assureLoaded(LazyBlock.java:276)
	at io.prestosql.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:267)
	at io.prestosql.operator.ScanFilterAndProjectOperator.lambda$recordProcessedInput$2(ScanFilterAndProjectOperator.java:311)
	at io.prestosql.spi.block.LazyBlock.assureLoaded(LazyBlock.java:276)
	at io.prestosql.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:267)
	at io.prestosql.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.<init>(DictionaryAwarePageProjection.java:97)
	at io.prestosql.operator.project.DictionaryAwarePageProjection.project(DictionaryAwarePageProjection.java:75)
	at io.prestosql.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:292)
	at io.prestosql.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:183)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:315)
	at io.prestosql.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:79)
	at io.prestosql.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:65)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at io.prestosql.operator.project.MergingPageOutput.getOutput(MergingPageOutput.java:111)
	at io.prestosql.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:296)
	at io.prestosql.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:231)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at io.prestosql.$gen.Presto_302_e_16____20190909_182335_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
**Caused by: java.io.InterruptedIOException: Reopen at position 1831791759 on tpch-test1/lineitem/20190729_173848_00087_ic489_646a5f6a-00cd-48f6-8991-2a3dfa4c3427: com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool
	at com.ibm.stocator.fs.cos.COSUtils.translateException(COSUtils.java:96)
	at com.ibm.stocator.fs.cos.COSInputStream.reopen(COSInputStream.java:127)
	at com.ibm.stocator.fs.cos.COSInputStream.lazySeek(COSInputStream.java:251)
	at com.ibm.stocator.fs.cos.COSInputStream.read(COSInputStream.java:305)
	at com.ibm.stocator.fs.cos.COSInputStream.readFully(COSInputStream.java:564)
	at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:111)
	at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:111)
	at** io.prestosql.plugin.hive.parquet.HdfsParquetDataSource.readInternal(HdfsParquetDataSource.java:104)
	... 35 more
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1163)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1109)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674)
	at 

Regards,
Bharath

**Comment by gilv** [comment]
@bharath0208 need more details to understand the issue... exception thrown from  org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
so i would start with configuring relevant keys to extend timeouts, pool, etc. You definitely not need to double resources for Stocator. See COS Connector optional configuration tuning from the https://github.com/CODAIT/stocator.

**Comment by bharath0208** [comment]
@gilv thanks for the response. What details do you need? I have tried optimizing the parameters like fs.cos.connection.maximum,fs.cos.connection.timeout in my core-site.xml. Still the issue continues. But when i increase the number of workers its able to handle the same amount of data. Thats the reason i asked is it required to increase resources when working with stocator.

**Comment by gilv** [comment]
@bharath0208 I wonder how this exception related stocator itself. The exception thrown from at io.prestosql.plugin.hive.parquet.HdfsParquetDataSource.readInternal(HdfsParquetDataSource.java:111) and originated in com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool and org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool.

Seems, something is not optimised, like some configuration. You don't need to add more resources to stocator, it even requires less then s3a. 
but in your environment, there might be some package differences between Stocator and s3a..is this the same SDK? are those the same dependencies, etc. May be there are other configurations that are being set by prestosql which are got to s3a and not to stocator... this is what i suggest you to check. 
We tested stocator many times, compared it with s3a, and so on. There are no issues and not need more resources, something just not optimized or some 3rd package in a wrong version.

by the way, there are much more configurations. that might be relevant, like fs.cos.threads.max, fs.cos.threads.keepalivetime, fs.cos.client.execution.timeout, etc.

**Comment by gilv** [comment]
@bharath0208 very interesting..thanks
