### ISSUE TITLE
stocator not working with spark-shell --  No FileSystem for scheme: cos

### ISSUE THREAD

**Issue by upendrasharma44** [CODAIT/stocator#229]
Hi,
I am trying to test stocator with my IBM COS account.
For quick testing I am using spak-mater and spark-worker-1 container-setup from https://github.com/big-data-europe/docker-spark
(spark-master:2.4.4-hadoop2.7).

I start spark-shell with stocator as shown below:
`/spark/bin/spark-shell --packages com.ibm.stocator:stocator:1.0.36`

I am observing and Exception: ` No FileSystem for scheme: cos` -- shown below

```
scala> sc.hadoopConfiguration.set("fs.cos.mycos.access.key", "215************")

scala> sc.hadoopConfiguration.set("fs.cos.mycos.secret.key", "1bd********************")

scala> sc.hadoopConfiguration.set("fs.cos.mycos.endpoint", "https://s3.us-east.cloud-object-storage.appdomain.cloud")

scala> val data = Array(1, 2, 3, 4, 5, 6, 7, 8)
data: Array[Int] = Array(1, 2, 3, 4, 5, 6, 7, 8)

scala> val distData = sc.parallelize(data)
distData: org.apache.spark.rdd.RDD[Int] = ParallelCollectionRDD[0] at parallelize at <console>:26

scala> distData.saveAsTextFile("cos://test-parquet.mycos/one1.txt")
java.io.IOException: No FileSystem for scheme: cos
  at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
  at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
  at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
  at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
  at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
  at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
  at org.apache.spark.internal.io.SparkHadoopWriterUtils$.createPathFromString(SparkHadoopWriterUtils.scala:55)
  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply$mcV$sp(PairRDDFunctions.scala:1066)
  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:1032)
  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:1032)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
  at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:1032)
  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply$mcV$sp(PairRDDFunctions.scala:958)
  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:958)
  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:958)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
  at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:957)
  at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply$mcV$sp(RDD.scala:1499)
  at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1478)
  at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1478)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
  at org.apache.spark.rdd.RDD.saveAsTextFile(RDD.scala:1478)
  ... 49 elided

scala>
```

**Comment by gilv** [comment]
@upendrasharma44 see this https://github.com/CODAIT/stocator#reference-stocator-in-the-core-sitexml

**Comment by upendrasharma44** [comment]
Thanks @gilv for your response.
It was not obvious which steps are necessary and which are optional, especially given that I did not even have `core-site.xml`.

I used the following `conf/core-site.xml` and it worked on my machine with a warning (did create the files) 

```
scala> distData.saveAsTextFile("cos://test-parquet.mycos/test3")
19/12/23 10:17:06 WARN COSAPIClient: file status test3 returned 404
```

configuration: `conf/core-site.xml`
```
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

<configuration>
    <property>
            <name>fs.stocator.scheme.list</name>
            <value>cos</value>
    </property>
    <property>
            <name>fs.cos.impl</name>
            <value>com.ibm.stocator.fs.ObjectStoreFileSystem</value>
    </property>
    <property>
            <name>fs.stocator.cos.impl</name>
            <value>com.ibm.stocator.fs.cos.COSAPIClient</value>
    </property>
    <property>
            <name>fs.stocator.cos.scheme</name>
            <value>cos</value>
    </property>
</configuration>
```

**Comment by gilv** [comment]
@upendrasharma44 you don't need core-sites.xml. You can provide all configurations with sc.hadoopConfiguration.set., e.g. sc.hadoopConfiguration.set("s.stocator.scheme.list", "cos"), etc.
