### ISSUE TITLE
Issues while deploying the stocator connector of Spark Java in Docker container

### ISSUE THREAD

**Issue by jasimwhd** [CODAIT/stocator#246]
Hi,

I am using Stocator connector _1.1.0_ in my JAVA Spark application _2.0.1_ to read/write data from IBM COS. My application works smoothly through local deployment. However, it fails to run in docker container mode with an exception:
```
Exception in thread "main" java.io.IOException: No FileSystem for scheme: null
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2421)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2428)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:88)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2467)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2449)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:367)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:287)
        at org.apache.spark.sql.catalyst.catalog.SessionCatalog.makeQualifiedPath(SessionCatalog.scala:115)
        at org.apache.spark.sql.catalyst.catalog.SessionCatalog.createDatabase(SessionCatalog.scala:145)
        at org.apache.spark.sql.catalyst.catalog.SessionCatalog.<init>(SessionCatalog.scala:89)
        at org.apache.spark.sql.internal.SessionState.catalog$lzycompute(SessionState.scala:95)
        at org.apache.spark.sql.internal.SessionState.catalog(SessionState.scala:95)
        at org.apache.spark.sql.internal.SessionState$$anon$1.<init>(SessionState.scala:112)
        at org.apache.spark.sql.internal.SessionState.analyzer$lzycompute(SessionState.scala:112)
        at org.apache.spark.sql.internal.SessionState.analyzer(SessionState.scala:111)
        at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:49)
        at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
        at org.apache.spark.sql.SparkSession.createDataFrame(SparkSession.scala:328)
..
```

I am using the following dockerfile to achieve my dockerization building and staging:

> # Build stage
> FROM maven:3.5-jdk-8 AS build
> COPY src /usr/src/app/src
> COPY pom.xml /usr/src/app
> ENV http_proxy "some correct proxy"
> ENV https_proxy "some correct proxy"
> RUN apt-get update \
>     && apt-get install --no-install-recommends -y openjfx \
>     && apt-get clean
> RUN mvn -f /usr/src/app/pom.xml clean package
> # Package stage
> FROM gcr.io/distroless/java
> COPY --from=build /usr/src/app/target/sample.jar /usr/app/sample.jar
> EXPOSE 8080
> ENTRYPOINT ["java","-jar","usr/app/sample.jar"]

My spark context configs:
 

>         spark.sparkContext().hadoopConfiguration().set("fs.hdfs.impl",
>                  org.apache.hadoop.hdfs.DistributedFileSystem.class.getName()
>          );
>          spark.sparkContext().hadoopConfiguration().set("fs.file.impl",
>                  org.apache.hadoop.fs.LocalFileSystem.class.getName()
>          );
>          spark.sparkContext().hadoopConfiguration().set("fs.cos.impl", "com.ibm.stocator.fs.ObjectStoreFileSystem");
>          spark.sparkContext().hadoopConfiguration().set("fs.stocator.scheme.list", "cos");
>          spark.sparkContext().hadoopConfiguration().set("fs.stocator.cos.impl", "com.ibm.stocator.fs.cos.COSAPIClient");
>          spark.sparkContext().hadoopConfiguration().set("fs.stocator.cos.scheme", "cos");
>          spark.sparkContext().hadoopConfiguration().
>                  set("fs.cos.cloud-object-storage.endpoint",
>                          "https://some.region.endpoint");
>          spark.sparkContext().hadoopConfiguration().set("fs.cos.cloud-object-storage.access.key", "some access key");
>          spark.sparkContext().hadoopConfiguration().set("fs.cos.cloud-object-storage.secret.key", "some secret key");
>          spark.sparkContext().hadoopConfiguration().set("fs.cos.cloud-object-storage.v2.signer.type", "false");
> 
Could you please let me know if there is an issue with my configs or there is a version incompatibility or something else?

**Comment by gilv** [comment]
@jasimwhd interesting...but exception is way above Stocator. It even can't find Stocator jar and fails at 
Exception in thread "main" java.io.IOException: No FileSystem for scheme: null
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2421)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2428)

sample.jar works locally and fails from Docker?
