### ISSUE TITLE
Passing IAM end point in stocator is not taking effect

### ISSUE THREAD

**Issue by GeethaSravanthi** [CODAIT/stocator#262]
Hi,

We are passing IAM end point in stocator as "fs.cos.myCos.iam.endpoint" and the api key as "fs.cos.myCos.iam.api.key". Does it actually use the IAM end point? The same api key works with the same IAM end point when done through postman and I can get the token successfully. However with stocator I am getting following issue.

**Caused by: com.ibm.stocator.thirdparty.cos.services.s3.model.AmazonS3Exception: Token retrieval from IAM service failed (Service: IAM; Status Code: 400; Error Code: null; Request ID: null), S3 Extended Request ID: null
	at com.ibm.stocator.thirdparty.cos.oauth.DefaultTokenProvider.retrieveToken(DefaultTokenProvider.java:160)
	at com.ibm.stocator.thirdparty.cos.oauth.DefaultTokenManager.retrieveToken(DefaultTokenManager.java:381)
	at com.ibm.stocator.thirdparty.cos.oauth.DefaultTokenManager.getToken(DefaultTokenManager.java:200)
	at com.ibm.stocator.thirdparty.cos.oauth.IBMOAuthSigner.sign(IBMOAuthSigner.java:64)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1271)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.ibm.stocator.thirdparty.cos.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3926)
	at com.ibm.stocator.thirdparty.cos.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3873)
	at com.ibm.stocator.thirdparty.cos.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1228)
	at com.ibm.stocator.thirdparty.cos.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1203)
	at com.ibm.stocator.fs.cos.COSAPIClient.getFileStatusKeyBased(COSAPIClient.java:675)
	at com.ibm.stocator.fs.cos.COSAPIClient.getFileStatus(COSAPIClient.java:596)**

**Comment by gilv** [comment]
@yangchenghuang 
   if (apiKey != null || token != null) {
      String serviceInstanceID = props.getProperty(IAM_SERVICE_INSTANCE_ID_PROPERTY);
      String iamEndpoint = props.getProperty(IAM_ENDPOINT_PROPERTY);
      String maxTokenRrety = props.getProperty(IAM_TOKEN_MAX_RETRY_PROPERTY);
      String tokenRefreshOffset = props.getProperty(IAM_TOKEN_REFRESH_OFFSET_PROPERTY);
      if (iamEndpoint != null) {
        LOG.debug("Setting custom IAM endpoint to {}", iamEndpoint);
        SDKGlobalConfiguration.IAM_ENDPOINT = iamEndpoint;
      }
      if (maxTokenRrety != null) {
        LOG.debug("Setting custom maximum token retry value to {}", maxTokenRrety);
        SDKGlobalConfiguration.IAM_MAX_RETRY = Integer.valueOf(maxTokenRrety).intValue();
      }
      if (tokenRefreshOffset != null) {
        LOG.debug("Setting custom token refresh offset to {}", tokenRefreshOffset);
        SDKGlobalConfiguration.IAM_REFRESH_OFFSET = Integer.valueOf(tokenRefreshOffset).intValue();
      }
      BasicIBMOAuthCredentials creds = null;
      if (apiKey != null) {
        LOG.debug("Using API key ");
        creds = new BasicIBMOAuthCredentials(apiKey, serviceInstanceID);
      } else if (token != null) {
        LOG.debug("Setting custom token");
        customToken = new CustomTokenManager(token);
        creds = new BasicIBMOAuthCredentials(customToken, serviceInstanceID);
      }
      credProvider = new AWSStaticCredentialsProvider(creds);
    }

**Comment by gilv** [comment]
@yangchenghuang can you check logs in DEBUG mode? May be some property set not correctly? Otherwise, we may want to open issue on COS SDK..but let's see first here what happens
