### ISSUE TITLE
Cannot change API key

### ISSUE THREAD

**Issue by benzim** [CODAIT/stocator#263]
This is on version `1.0.36-ibm-sdk`.
### Steps to recreate
1. Connect to a bucket by setting the property `fs.cos.<service>.iam.api.key` to a valid API key that has access to the bucket.
2. Try to connect to a second bucket that the first API key does not have access to by setting the property `fs.cos.<service>.iam.api.key` to a second API key that does have access to the second bucket.
3. Attempts to access the second bucket fails with
```
Caused by: com.ibm.stocator.thirdparty.cos.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: bbde56ac-78da-41df-97f2-ae7d77270a66), S3 Extended Request ID: null
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.ibm.stocator.thirdparty.cos.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3926)
	at com.ibm.stocator.thirdparty.cos.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3873)
	at com.ibm.stocator.thirdparty.cos.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1228)
	at com.ibm.stocator.thirdparty.cos.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1203)
	at com.ibm.stocator.fs.cos.COSAPIClient.getFileStatusKeyBased(COSAPIClient.java:675)
	at com.ibm.stocator.fs.cos.COSAPIClient.getFileStatus(COSAPIClient.java:596)
	... 105 more
```
It seems like the API key is getting cached because the first bucket can still be accessed even if `fs.cos.<service>.iam.api.key` is set to the second API key which does not have access to the first bucket.

**Comment by gilv** [comment]
@benzim you are using same <service> name? If you use other, you can access... I will check if it cached in Spark against connector once it's initiated or some issue in the connector itself

**Comment by benzim** [comment]
I am using the same `<service>` name for both. Should I be using a different `<service>` name for each bucket?

**Comment by gilv** [comment]
@benzim it will work with different service names, but i assume it can also work with one service name for different buckets. You need to verify you set ALL keys for the 2nd bucket and not just change API key. Stocator by itself doesn't cache this data. It's Spark that once connector is initiated it caches it and never call init() again. But Spark does it per URL.

**Comment by benzim** [comment]
@gilv What other keys do I need to set? The endpoint is the same for both buckets.

**Comment by gilv** [comment]
@benzim let me test the same scenario, i will then spot what is wrong

**Comment by gilv** [comment]
@benzim it actually works for me..may be you change api key in a wrong way, so actually previous one is use for the new bucket?
