### ISSUE TITLE
Unable to read from Cloud Object storage when the begining of the path contains "/"

### ISSUE THREAD

**Issue by charles2588** [CODAIT/stocator#268]
The COS bucket contains top level folder called "/abc".
Use ibmos2spark for making cos url.
Spark 2.4 with Python 3.6. => IBM Watson studio on Cloud.

input_bucket= "/abc"

df = spark.read\
  .format('csv')\
  .option('header', 'true')\
  .load(spark_cos.url(input_file, input_bucket))

Trying to read it in Spark results in
Py4JJavaError: An error occurred while calling o477.load.
: org.apache.spark.sql.AnalysisException: Path does not exist: cos://cosbucket.servicename/abc/train.csv;
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:576)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:559)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:355)
	at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:559)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:373)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:242)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:230)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:821)

During handling of the above exception, another exception occurred:
'Path does not exist: cos://cosbucket.servicename/abc/train.csv;'

It seems stocator connector is escaping the "/" or removing it. I infact tried adding "//////" and all were reduced to "/".

@gilv can you please help.

**Comment by mrmadira** [comment]
Hi @charles2588  - Is this still an issue Charles?
Can you give a repro of how to create the top level folder with a leading / in the first place? 
I could not create from UI or from HDFS command..

**Comment by charles2588** [comment]
![image](https://user-images.githubusercontent.com/5734421/116836278-c38ba200-ab7a-11eb-91ec-521103dcd2ce.png)
I cannot upload an object with prefix / anymore so i cannot reproduce it anymore.
after refresh, the / prefix go away so no longer a valid usecase. 
![image](https://user-images.githubusercontent.com/5734421/116836318-e28a3400-ab7a-11eb-80f4-4066fd264162.png)
