### ISSUE TITLE
FileNotFoundException while accessing objects from hive-style partitioned data stored on an OCS cluster

### ISSUE THREAD

**Issue by djain13** [CODAIT/stocator#274]
FileNotFoundException while accessing objects from hive-style partitioned data stored on an OCS cluster. Below is the exact exception trace:
```
21/03/31 09:48:14 [WARN] o.a.s.s.TaskSetManager - Lost task 375.0 in stage 0.0 (TID 375, 10.254.3.219, executor 71): java.io.FileNotFoundException: Not found cos://tpcds.service/sf10000_parquet/catalog_sales/cs_sold_date_sk%3D2451191
	at com.ibm.stocator.fs.cos.COSAPIClient.getFileStatus(COSAPIClient.java:667)
	at com.ibm.stocator.fs.ObjectStoreFileSystem.getFileStatus(ObjectStoreFileSystem.java:513)
	at com.ibm.stocator.fs.ObjectStoreFileSystem.listStatus(ObjectStoreFileSystem.java:356)
	at com.ibm.stocator.fs.ObjectStoreFileSystem.listStatus(ObjectStoreFileSystem.java:334)
	at com.ibm.stocator.fs.ObjectStoreFileSystem.listStatus(ObjectStoreFileSystem.java:340)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex$.listLeafFiles(InMemoryFileIndex.scala:322)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex$.$anonfun$bulkListLeafFiles$6(InMemoryFileIndex.scala:237)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex$$$Lambda$790/000000005C0A0EB0.apply(Unknown Source)
```
Environment details:
CPDv3.5, Stocator build v1.1.3

**Comment by djain13** [comment]
After some code inspection, I found a code path in `list operation` where encoded common-prefix returned by OCS are not handled and being passed to the client(Spark), which leads to the above FNF exception. I did see this PR https://github.com/CODAIT/stocator/pull/250 but unfortunately, it's not covering this code path.

**Comment by djain13** [comment]
@gilv Created this PR https://github.com/CODAIT/stocator/pull/275 to address the issue
cc @guykhazma
