### ISSUE TITLE
Get Bucket not found

### ISSUE THREAD

**Issue by n16** [CODAIT/stocator#331]
I am using stocator but I'm getting the following error, despite the bucket being existed: 

I tried many different approaches but no luck. Can you please let me know how I can resolve this issue. This happens on 5 spark workers, when I reduced them to 1, it works fine.

```
23/06/23 22:38:06 WARN TaskSetManager - Lost task 0.1 in stage 8.0 (TID 106) (172.26.6.46 executor 1): com.ibm.stocator.thirdparty.cos.services.s3.model.AmazonS3Exception: The specified bucket does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: da6ce0c0-3f3a-4a6a-81e1-1b9e941e8b8b; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1862)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1415)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1384)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
	at com.ibm.stocator.thirdparty.cos.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
	at com.ibm.stocator.thirdparty.cos.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5637)
	at com.ibm.stocator.thirdparty.cos.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5584)
	at com.ibm.stocator.thirdparty.cos.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5578)
	at com.ibm.stocator.thirdparty.cos.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:840)
	at com.ibm.stocator.fs.cos.COSAPIClient.getFileStatus(COSAPIClient.java:650)
	at com.ibm.stocator.fs.ObjectStoreFileSystem.getFileStatus(ObjectStoreFileSystem.java:513)
	at org.apache.parquet.hadoop.util.HadoopInputFile.fromPath(HadoopInputFile.java:39)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:39)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.footerFileMetaData$lzycompute$1(ParquetFileFormat.scala:268)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.footerFileMetaData$1(ParquetFileFormat.scala:267)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.$anonfun$buildReaderWithPartitionValues$2(ParquetFileFormat.scala:270)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$Lambda$686/0x000000006c3df5d0.apply(Unknown Source)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:127)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:187)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:104)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.sort(UnsafeExternalRowSorter.java:225)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$.$anonfun$prepareShuffleDependency$10(ShuffleExchangeExec.scala:369)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$$$Lambda$692/0x000000006c502220.apply(Unknown Source)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.RDD$$Lambda$688/0x000000006c4b72c0.apply(Unknown Source)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.executor.Executor$TaskRunner$$Lambda$468/0x000000006c042a80.apply(Unknown Source)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:827)

```

**Comment by n16** [comment]
So, there is a template I am using spark-3.2-jaas-v2-cp4d-template which require to provide number of workers. When the below num_workers is set to 1, the Spark job works fine. When it is more than 1 (5 in this example) the above error is thrown. 

```
      "size": {
          "num_workers": 5,
          "worker_size": {
              "cpu": 2,
              "memory": "2g"
          },
          "driver_size": {
              "cpu": 2,
              "memory": "2g"
          }
      },
```

**Comment by n16** [comment]
This issue can be marked as resolved. @mrmadira helped me to resolve this issue. Thank you. 
For anyone else who might encounter the same issue, the problem can be resolved by assigning unique _service_ names for each COS Read or Write, as following:

```
sc.sparkContext.hadoopConfiguration
      .set(s"fs.cos.$service.endpoint", parameters(ConstsOptions.ENDPOINT))
    sc.sparkContext.hadoopConfiguration
      .set(s"fs.cos.$service.access.key", parameters(ConstsOptions.ACCESSKEY))
    sc.sparkContext.hadoopConfiguration
      .set(s"fs.cos.$service.secret.key", parameters(ConstsOptions.SECRETKEY))
```
where _$service_ value is a unique for each Read or Write within the same application.
